# Generated by Django 5.0 on 2025-10-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]


